apiVersion: v1
kind: Pod
metadata:
  name: annotation
  labels: 
    course: DevOps
    Trainer: "siva"
  annotations:
    com.roboshop.training.duration: "120 hours"
    jenkins.url: "https://jenkins.com/roboshop/catalogue#45"
spec:
  containers:
  - name: hello-pod
    image: nginx
    ports:
      containerPort: 80